# Generated by Django 3.0.4 on 2020-03-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shisheratiapp', '0002_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
