# Generated by Django 3.0.4 on 2020-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shisheratiapp', '0004_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_by',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
