# Generated by Django 3.0.4 on 2020-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shisheratiapp', '0005_task_remind_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='remind_by',
            field=models.TimeField(default=(0, 0, 0)),
        ),
    ]
